export	const ADATLISTA = [
    {
        név:"Dézi",
        fajta:"keverék",
        év:"12"
    },
    {
        név:"lajos",
        fajta:"keverék",
        év:"12"
    },
    {
        név:"szuli",
        fajta:"terrier",
        év:"13"
    },
    {
        név:"jnoi",
        fajta:"west",
        év:"17"
    }
];