export	const ADATLISTA = [
    {
        nev:"Dézi",
        fajta:"keverék",
        kor:2.5,
        kép:"kutya/kutya.png"
    },
    {
        nev:"lajos",
        fajta:"keverék",
        kor:1,
        kép:"kutya/kutya2.png"
    },
    {
        nev:"szuli",
        fajta:"terrier",
        kor:10,
        kép:"kutya/kutya3.png"
    },
    {
        nev:"jnoi",
        fajta:"west",
        kor:17,
        kép:"kutya/kutya4.png"
    }
];